[package]
name = "lox-interpreter"
version = "0.1.0"
authors = ["Mykyta Cheshulko <chehhmann.nick@gmail.com>"]
edition = "2021"
rust-version = "1.80"

[dependencies]
anyhow = "1.0.68"
clap = { version = "4.5.17", features = ["derive"] }
miette = { version = "7.2.0", features = ["fancy"] }
